
import mysql.connector
mydb =mysql.connector.connect(
host="localhost",
user="root",
passwd=""
)

    


mycursor=mydb.cursor()


mycursor.execute("create database parking")
mycursor.execute("CREATE TABLE parking_number (Number INTEGER(10))")

#mycursor.execute("SHOW TABLES")



sqlFormula = "INSERT INTO parking_number (Number) VALUES(%s)"   

parking1 =(1)
parking2 =(2)
parking3 =(3)
parking4 =(4)
parking5 =(5)
parking6 =(6)
parking7 =(7)
parking8 =(8)
parking9 =(9)
parking10 =(10)
parking11 =(11)
parking12 =(12)
parking13 =(13)
parking14 =(14)
parking15 =(15)
parking16 =(16)
parking17 =(17)
parking18 =(18)
parking19 =(19)
parking20 =(20)
parking21 =(21)
parking22 =(22)
parking23 =(23)
parking24 =(24)
parking25 =(25)
parking26 =(26)
parking27 =(27)
parking28 =(28)
parking29 =(29)
parking30 =(30)
parking31 =(31)
parking32 =(32)
parking33 =(33)
parking34 =(34)
parking35 =(35)
parking36 =(36)
parking37 =(37)
parking38 =(38)
parking39 =(39)
parking40 =(40)
parking41 =(41)
parking42 =(42)
parking43 =(43)
parking44 =(44)
parking45 =(45)
parking46 =(46)
parking47 =(47)
parking48 =(48)
parking49 =(49)
parking50 =(50)
parking51 =(51)
parking52 =(52)
parking53 =(53)

mycursor.execute(sqlFormula, parking1)
mycursor.execute(sqlFormula, parking2)
mycursor.execute(sqlFormula, parking3)
mycursor.execute(sqlFormula, parking4)
mycursor.execute(sqlFormula, parking5)
mycursor.execute(sqlFormula, parking6)
mycursor.execute(sqlFormula, parking7)
mycursor.execute(sqlFormula, parking8)
mycursor.execute(sqlFormula, parking9)
mycursor.execute(sqlFormula,parking10)
mycursor.execute(sqlFormula, parking11)
mycursor.execute(sqlFormula, parking12)
mycursor.execute(sqlFormula, parking13)
mycursor.execute(sqlFormula, parking14)
mycursor.execute(sqlFormula, parking15)
mycursor.execute(sqlFormula, parking16)
mycursor.execute(sqlFormula, parking17)
mycursor.execute(sqlFormula, parking18)
mycursor.execute(sqlFormula, parking19)
mycursor.execute(sqlFormula, parking20)
mycursor.execute(sqlFormula, parking21)
mycursor.execute(sqlFormula, parking22)
mycursor.execute(sqlFormula, parking23)
mycursor.execute(sqlFormula, parking24)
mycursor.execute(sqlFormula, parking25)
mycursor.execute(sqlFormula, parking26)
mycursor.execute(sqlFormula, parking27)
mycursor.execute(sqlFormula, parking28)
mycursor.execute(sqlFormula, parking29)
mycursor.execute(sqlFormula, parking30)
mycursor.execute(sqlFormula, parking31)
mycursor.execute(sqlFormula, parking32)
mycursor.execute(sqlFormula, parking33)
mycursor.execute(sqlFormula, parking34)
mycursor.execute(sqlFormula, parking35)
mycursor.execute(sqlFormula, parking36)
mycursor.execute(sqlFormula, parking36)
mycursor.execute(sqlFormula, parking37)
mycursor.execute(sqlFormula, parking38)
mycursor.execute(sqlFormula, parking39)
mycursor.execute(sqlFormula, parking40)
mycursor.execute(sqlFormula, parking41)
mycursor.execute(sqlFormula, parking42)
mycursor.execute(sqlFormula, parking43)
mycursor.execute(sqlFormula, parking44)
mycursor.execute(sqlFormula, parking45)
mycursor.execute(sqlFormula, parking46)
mycursor.execute(sqlFormula, parking47)
mycursor.execute(sqlFormula, parking48)
mycursor.execute(sqlFormula, parking49)
mycursor.execute(sqlFormula, parking50)
mycursor.execute(sqlFormula, parking51)
mycursor.execute(sqlFormula, parking52)
mycursor.execute(sqlFormula, parking53)

mydb.commit()
